### ISSUE TITLE
Wildfly console log error: NashornScriptEngineFactory not found

### ISSUE THREAD

**Issue by tjdurden** [surevine/gateway#71]
Noticed the following occurring regularly in:    /var/log/wildfly/console.log

12:23:13,065 INFO  [com.surevine.community.gateway.hooks.FileImportContextHook] (FileImportContextHook) Reading metadata file.
12:23:13,068 INFO  [com.surevine.community.gateway.hooks.Hooks] (FileImportContextHook) STARTING [com.surevine.community.gateway.hooks.JavascriptPreImportHook]
12:23:13,077 ERROR [stderr] (FileImportContextHook) ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not found
12:23:13,079 INFO  [com.surevine.community.gateway.hooks.JavascriptPreImportHook] (FileImportContextHook) STARTING javascript hook [/opt/gateway/console/gateway-management-1.0/conf/rules/global-import.js].
12:23:13,084 INFO  [com.surevine.community.gateway.hooks.JavascriptPreImportHook] (FileImportContextHook) COMPLETE javascript hook [/opt/gateway/console/gateway-management-1.0/conf/rules/global-import.js].

**Comment by JonnyHeavey** [comment]
Accrding to the following post, this message is only informative, and should cause no issues:

https://developer.jboss.org/thread/239467?start=0&tstart=0

**Comment by JonnyHeavey** [comment]
Closing as issue not causing any impact
